// GENERATED by scripts/build-flag-colors.mjs - do not edit by hand.
//
// Dominant colours of each country's flag, most of the flag first, counted off
// the real pixels of the flag image. The map paints a bubble with the first as
// its fill and the second as its ring, which is what makes a French bubble read
// as blue-and-white rather than as "some blue".

export const FLAG_COLORS: Record<string, string[]> = {
  AD: ['#10069f', '#d50032', '#fedd00'], // Andorra
  AE: ['#c8102e', '#00843d', '#ffffff'], // United Arab Emirates
  AF: ['#000000', '#007a36', '#d32011'], // Afghanistan
  AL: ['#ff0000', '#010000'], // Albania
  AM: ['#d90012', '#0033a0', '#f2a800'], // Armenia
  AO: ['#cc092f', '#000000'], // Angola
  AR: ['#74acdf', '#ffffff'], // Argentina
  AT: ['#c8102e', '#ffffff'], // Austria
  AU: ['#012169', '#e4002b'], // Australia
  AZ: ['#00b5e2', '#509e2f', '#ef3340'], // Azerbaijan
  BA: ['#002395', '#fecb00'], // Bosnia and Herzegovina
  BD: ['#006a4e', '#f42a41'], // Bangladesh
  BE: ['#000000', '#ef3340', '#fdda25'], // Belgium
  BF: ['#ef2b2d', '#009e49'], // Burkina Faso
  BG: ['#ffffff', '#00966e', '#d62612'], // Bulgaria
  BH: ['#da291c', '#ffffff'], // Bahrain
  BI: ['#43b02a', '#c8102e', '#ffffff'], // Burundi
  BJ: ['#008751', '#fcd116', '#e8112d'], // Benin
  BN: ['#f7e017', '#ffffff', '#000000'], // Brunei
  BO: ['#d32011', '#00702d', '#f0e53c'], // Bolivia
  BR: ['#009440', '#ffcb00', '#302681'], // Brazil
  BW: ['#6da9d2', '#000000', '#edf4f9'], // Botswana
  BY: ['#ce1720', '#007c30'], // Belarus
  BZ: ['#171696', '#d90f19'], // Belize
  CA: ['#ff0000', '#ffffff'], // Canada
  CD: ['#007fff', '#ce1021', '#f6d418'], // DR Congo
  CF: ['#ffce00', '#ffffff', '#289728'], // Central African Republic
  CG: ['#009543', '#dc241f', '#fbde4a'], // Congo
  CH: ['#ff0000', '#ffffff'], // Switzerland
  CL: ['#da291c', '#ffffff', '#0032a0'], // Chile
  CM: ['#fcd116', '#007a5e', '#ce1126'], // Cameroon
  CN: ['#ee1c25'], // China
  CO: ['#ffcd00', '#003087', '#c8102e'], // Colombia
  CR: ['#001489', '#ffffff', '#da291c'], // Costa Rica
  CU: ['#002a8f', '#ffffff', '#cb1515'], // Cuba
  CY: ['#ffffff', '#d67900'], // Cyprus
  CZ: ['#d7141a', '#ffffff', '#11457e'], // Czechia
  DE: ['#000000', '#dd0000', '#ffce00'], // Germany
  DK: ['#c8102e', '#ffffff'], // Denmark
  DO: ['#002d62', '#ce1126', '#ffffff'], // Dominican Republic
  DZ: ['#ffffff', '#006633'], // Algeria
  EC: ['#ffdd00', '#ed1c24', '#034ea2'], // Ecuador
  EE: ['#0072ce', '#ffffff', '#000000'], // Estonia
  EG: ['#ce1126', '#000000', '#ffffff'], // Egypt
  ER: ['#e4002b', '#43b02a', '#418fde'], // Eritrea
  ES: ['#ad1519', '#fabd00'], // Spain
  ET: ['#078930', '#da121a', '#fcdd09'], // Ethiopia
  FI: ['#ffffff', '#002f6c'], // Finland
  FJ: ['#62b5e5', '#c8102e'], // Fiji
  FR: ['#002654', '#ce1126', '#ffffff'], // France
  GA: ['#009e60', '#fcd116', '#3a75c4'], // Gabon
  GB: ['#c8102e', '#ffffff', '#012169'], // United Kingdom
  GE: ['#ffffff', '#ff0000'], // Georgia
  GH: ['#ce1126', '#006b3f', '#fcd116'], // Ghana
  GN: ['#ce1126', '#009460', '#fcd116'], // Guinea
  GR: ['#0d5eaf', '#ffffff'], // Greece
  GT: ['#4997d0', '#ffffff'], // Guatemala
  GY: ['#2a936a', '#be1e2d', '#ffc20e'], // Guyana
  HK: ['#ee1c25', '#fffdfd'], // Hong Kong
  HN: ['#00bce4', '#ffffff'], // Honduras
  HR: ['#171796', '#ff0000', '#ffffff'], // Croatia
  HT: ['#00209f', '#d21034'], // Haiti
  HU: ['#ce2939', '#ffffff', '#477050'], // Hungary
  ID: ['#ff0000', '#ffffff'], // Indonesia
  IE: ['#169b62', '#ff883e', '#ffffff'], // Ireland
  IL: ['#ffffff', '#0038b8'], // Israel
  IN: ['#ff6820', '#046a38', '#ffffff'], // India
  IQ: ['#cd1125', '#000000', '#ffffff'], // Iraq
  IR: ['#ffffff', '#239f40', '#da0000'], // Iran
  IS: ['#02529c', '#dc1e35', '#ffffff'], // Iceland
  IT: ['#009246', '#ce2b37', '#ffffff'], // Italy
  JM: ['#007749', '#000000', '#ffb81c'], // Jamaica
  JO: ['#000000', '#007a3d', '#ce1126'], // Jordan
  JP: ['#ffffff', '#bc002d'], // Japan
  KE: ['#006600', '#000000', '#bb0000'], // Kenya
  KG: ['#ff0000'], // Kyrgyzstan
  KH: ['#032ea1', '#e00025'], // Cambodia
  KR: ['#ffffff', '#cd2e3a', '#0047a0'], // South Korea
  KW: ['#007a3d', '#ce1126', '#ffffff'], // Kuwait
  KZ: ['#00abc2', '#52c091'], // Kazakhstan
  LA: ['#ce1126', '#002868', '#ffffff'], // Laos
  LB: ['#d31624', '#ffffff'], // Lebanon
  LK: ['#ffbe29', '#8d153a', '#00534e'], // Sri Lanka
  LR: ['#bf0a30', '#ffffff', '#002868'], // Liberia
  LT: ['#fdb913', '#006a44', '#c1272d'], // Lithuania
  LU: ['#ed2939', '#ffffff', '#00a1de'], // Luxembourg
  LV: ['#9d2235', '#ffffff'], // Latvia
  LY: ['#000000', '#e70013', '#239e46'], // Libya
  MA: ['#c1272d'], // Morocco
  MD: ['#0046ae', '#cc092f', '#ffd200'], // Moldova
  ME: ['#e30000', '#ffc000'], // Montenegro
  MG: ['#ffffff', '#fc3d32', '#007e3a'], // Madagascar
  MK: ['#d82126', '#f8e92e'], // North Macedonia
  ML: ['#14b53a', '#ce1126', '#fcd116'], // Mali
  MM: ['#fecb00', '#ea2839', '#34b233'], // Myanmar
  MN: ['#da2031', '#0066b2'], // Mongolia
  MT: ['#cf142b', '#ffffff'], // Malta
  MX: ['#006847', '#ce1126', '#ffffff'], // Mexico
  MY: ['#000066', '#ffffff', '#d83f3f'], // Malaysia
  MZ: ['#fce100', '#007168', '#000000'], // Mozambique
  NA: ['#009543', '#003580', '#d21034'], // Namibia
  NG: ['#008751', '#ffffff'], // Nigeria
  NI: ['#0067c6', '#ffffff'], // Nicaragua
  NL: ['#ae1c28', '#ffffff', '#21468b'], // Netherlands
  NO: ['#ba0c2f', '#00205b', '#ffffff'], // Norway
  NP: ['#dc143c', '#003893', '#ffffff'], // Nepal
  NZ: ['#012169', '#c8102e'], // New Zealand
  OM: ['#df1a23', '#ffffff', '#007e3c'], // Oman
  PA: ['#ffffff', '#072357', '#da121a'], // Panama
  PE: ['#d91023', '#ffffff'], // Peru
  PH: ['#0038a8', '#ce1126', '#ffffff'], // Philippines
  PK: ['#01411c', '#ffffff'], // Pakistan
  PL: ['#ffffff', '#dc143c'], // Poland
  PT: ['#ff0000', '#006600'], // Portugal
  PY: ['#d52b1e', '#0038a8', '#ffffff'], // Paraguay
  QA: ['#8a1538', '#ffffff'], // Qatar
  RO: ['#002b7f', '#ce1126', '#fcd116'], // Romania
  RS: ['#ffffff', '#c6363c', '#0c4076'], // Serbia
  RU: ['#ffffff', '#0039a6', '#d52b1e'], // Russia
  RW: ['#00a3e0', '#fad201', '#20603d'], // Rwanda
  SA: ['#005430'], // Saudi Arabia
  SD: ['#d21034', '#000000', '#ffffff'], // Sudan
  SE: ['#005293', '#fecb00'], // Sweden
  SG: ['#ffffff', '#ed2939'], // Singapore
  SI: ['#ff0000', '#0000ff', '#ffffff'], // Slovenia
  SK: ['#ee1c25', '#ffffff', '#0b4ea2'], // Slovakia
  SN: ['#00853f', '#e31b23', '#fdef42'], // Senegal
  SO: ['#418fde'], // Somalia
  SR: ['#377e3f', '#b40a2d', '#ffffff'], // Suriname
  SV: ['#0047ab', '#ffffff'], // El Salvador
  SY: ['#007a3d', '#000000', '#ffffff'], // Syria
  TD: ['#002664', '#c60c30', '#fecb00'], // Chad
  TG: ['#006a4e', '#ffce00', '#d21034'], // Togo
  TH: ['#2d2a4a', '#a51931', '#f4f5f8'], // Thailand
  TJ: ['#ffffff', '#cc0000', '#006600'], // Tajikistan
  TM: ['#00843d'], // Turkmenistan
  TN: ['#e70013', '#fffefe'], // Tunisia
  TR: ['#e30a17'], // Turkey
  TT: ['#da1a35', '#000000'], // Trinidad and Tobago
  TW: ['#fe0000', '#000094'], // Taiwan
  TZ: ['#1eb53a', '#00a3dd', '#000000'], // Tanzania
  UA: ['#005bbb', '#ffd500'], // Ukraine
  UG: ['#fcdc04', '#000000', '#d90000'], // Uganda
  US: ['#ffffff', '#b31942', '#0d3363'], // United States
  UY: ['#ffffff', '#0038a8'], // Uruguay
  UZ: ['#ffffff', '#308738', '#3181f7'], // Uzbekistan
  VE: ['#ffcc00', '#cf142b', '#00247d'], // Venezuela
  VN: ['#ff0000', '#ffeb00'], // Vietnam
  YE: ['#ce1126', '#ffffff', '#000000'], // Yemen
  ZA: ['#007749', '#e03c31', '#001489'], // South Africa
  ZM: ['#198a00', '#ef7d00', '#de2010'], // Zambia
  ZW: ['#006400', '#ffd200', '#d40000'], // Zimbabwe
};
